version: "2"

linters:
  enable:
    - llmci
  settings:
    custom:
      llmci:
        type: "module"
        description: "使用LLM分析Go代码文件"
        original-url: github.com/hsyue/gcl-llmci
        settings:
          file_patterns: 
            - "*.go"
            - "*_test.go"
          prompt: "请分析这个Go代码文件，重点关注：1. 代码质量和最佳实践 2. 潜在的bug和安全问题 3. 性能优化建议 4. 代码可读性和维护性"
          api_url: "https://api.openai.com/v1/chat/completions"
          api_token: "your-openai-api-token-here"
          timeout: 30